NBRHC/Models/Gallery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace NBRHC.Models
{
    public class Gallery
    {
        [Key]
        public int ImageID { get; set; }

        [Required, StringLength(50), Display(Name = "Alt")]
        public string ImageAlt { get; set; }

        [Required, StringLength(50), Display(Name = "Name")]
        public string ImageName { get; set; }

        [StringLength(50)]
        public string ImageType { get; set; }

    }
}

NBRHC/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using System.Web;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using NBRHC.Models;
using NBRHC.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

namespace NBRHC.Controllers
{
    //Note: This controller references Christine Bittle's http5204-blog-aspcore example.
    //Comments as well as code may look similar for learning purposes but is applied to this specific feature
    public class GalleryController : Controller
    {
        //Make a Db Context for CRUD
        private readonly NBRHCCMSContext db;
        //This is for file upload
        private readonly IHostingEnvironment _env;
        //We need the usermanager class to get things like the id or name
        private readonly UserManager<ApplicationUser> _userManager;
        //This function will return the current user at some point when called
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public GalleryController(NBRHCCMSContext context, UserManager<ApplicationUser> usermanager, IHostingEnvironment env)
        {
            //When gallery controller is created, it creates three things
            //Db Context for CRUD
            db = context;
            //User manager for getting the current logged in user
            _userManager = usermanager;
            //Hosting environment for getting filepaths
            _env = env;
        }

        public async Task<int> GetUserDetails(ApplicationUser user)
        {
            //UserState
            //0 => Public user 
            //1 => User but has no admin account 
            //2 => User has admin account 
            if (user == null) return 0;
            if (user.AdminID == null) return 1;  
            else
            {
                return 2; 
            }
        }

        // GET: Gallery
        public ActionResult Index()
        {
            //If the app calls for index of gallery redirect to Views/List.cshtml
            return RedirectToAction("List");
        }

        public async Task<ActionResult> List(int pagenum)
        {            
            //Get current user
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

            //Info on user
            ViewData["UserState"] = userstate;
            ViewData["UserAdminID"] = 0;

            //Pagination
            //Referenced from:
            //Christine Bittle's http5204-blog-aspcore example BlogController.cs line 135
            var _gallery = await db.Gallery.ToListAsync(); //Get a list of our rows in the gallery table
            int imagecount = _gallery.Count(); //Set total number of rows
            int perpage = 5; //Set number of rows we want max to show
            int maxpage = (int)Math.Ceiling((decimal)imagecount / perpage) - 1; //Max shown per page, Math.Ceiling rounds up
            if (maxpage < 0) maxpage = 0; //Bounds
            if (pagenum < 0) pagenum = 0; //Bounds
            if (pagenum > maxpage) pagenum = maxpage; //Bounds
            int start = perpage * pagenum;
            //Show page numbers and which page the user is on
            ViewData["pagenum"] = (int)pagenum; 
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }

            if(userstate == 2)
            {
                ViewData["UserAdminID"] = user.AdminID;
            }
            
            return View(await db.Gallery.Skip(start).Take(perpage).ToListAsync());
        }

        // GET: Gallery/Details
        public async Task<ActionResult> Details(int? id)
        {
            //Get our current user
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);
            ViewData["UserState"] = userstate;

            //If user is not logged in 
            if (userstate == 0)
            {
                return new StatusCodeResult(400);
            }

            if(userstate == 2)
            {
                ViewData["UserAdminID"] = user.AdminID;
            }

            return View(await db.Gallery.SingleOrDefaultAsync(i => i.ImageID == id));
        }

        // GET: Gallery/Create
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New([Bind("ImageID, ImageAlt, ImageName")] Gallery gallery, IFormFile galleryimg)
        {
            //Referenced from Christine Bittle's AuthorController.cs http5204-blog-aspcore
            var user = await GetCurrentUserAsync(); //Get current user
            var userstate = await GetUserDetails(user);
            if (userstate == 0) return Forbid(); //Forbid because they don't have an account
            if (userstate == 1) return Forbid(); //Forbid because they are not an admin

            var webRoot = _env.WebRootPath;

            if(galleryimg != null)
            {
                if (galleryimg.Length > 0)
                {
                    //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                    var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                    var extension = Path.GetExtension(galleryimg.FileName).Substring(1);

                    if (valtypes.Contains(extension))
                    {
                        //Get file name
                        string pic = galleryimg.FileName;
                        //Set ImageName to pictures file name
                        gallery.ImageName = pic;

                        //string fn is qual to filename.extension
                        string fn = pic + "." + extension;

                        //Get direct path to wwwroot/images/gallery
                        string path = Path.Combine(webRoot, "images/gallery");
                        path = Path.Combine(path, fn);

                        //Save the file
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            galleryimg.CopyTo(stream);
                        }
                        //let the model know that there is a picture with an extension
                        gallery.ImageType = extension;

                    }
                    else
                    {
                        TempData["AddFail"] = "Failed to add image";
                        return RedirectToAction("Index");
                    }
                }
            }
            db.Gallery.Add(gallery);
            db.SaveChanges();
            TempData["AddSuccess"] = "Image successfully added";
            return RedirectToAction("Index");

        }

        // GET: Gallery/Edit
        public async Task<ActionResult> Edit(int? id)
        {
            //Get current user, if not logged in or not an admin then forbid
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

            //If user not logged in 
            if (userstate == 0)
            {
                return new StatusCodeResult(400);
            }
            
            //Find specific image in the gallery we are editing
            Gallery gallery = db.Gallery.Find(id);

            if (gallery == null)
            {
                return NotFound();
            }

            if (userstate == 0)
            {
                return Forbid();
            }
            if (userstate == 1)
            {
                return Forbid();
            }

            return View(gallery);

        }

        // POST: Gallery/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("ImageID, ImageAlt, ImageName, ImageType")] Gallery gallery, IFormFile galleryimg)
        {
            var user = await GetCurrentUserAsync();
            var userstate = await GetUserDetails(user);

            //Must be logged in 
            if (userstate == 0)
            {
                return Forbid();
            }
            //If the user is not an admin they cannot edit the gallery
            if (userstate == 1)
            {
                return Forbid();
            }

            var webRoot = _env.WebRootPath;

            if (galleryimg != null)
            {
                if (galleryimg.Length > 0)
                {
                    //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                    var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                    var extension = Path.GetExtension(galleryimg.FileName).Substring(1);

                    if (valtypes.Contains(extension))
                    {
                        //Get file name
                        string pic = galleryimg.FileName;
                        //Set ImageName to pictures file name
                        gallery.ImageName = pic;

                        //string fn is qual to filename.extension
                        string fn = pic + "." + extension;

                        //Get direct path to wwwroot/images/gallery
                        string path = Path.Combine(webRoot, "images/gallery");

NBRHC/Views/Gallery/Details.cshtml
@model NBRHC.Models.Gallery

@{
    ViewData["Title"] = "Image Details";
}
@if (TempData["EditSuccess"] != null)
{
    <div class="alert alert-success text-center" role="alert">
        <strong>Image succeessfully edited</strong>
    </div>
}
else if (TempData["EditFail"] != null)
{
    <div class="alert alert-danger text-center" role="alert">
        <strong>Failed to edit image</strong>
        <div>File type must be: jpeg, jpg, png or gif</div>
    </div>
}

<div class="container">
    <h1>Image Details</h1>
    <hr />
    <h3><u>Image alternative text:</u></h3>
    <h3>@Model.ImageAlt</h3>
    <h3><u>Image file name:</u></h3>
    <h3>@Model.ImageName</h3>
    <img src="~/images/gallery/@Model.ImageName.@Model.ImageType" class="imagePreview" />
    <form method="get" action="/Gallery/Edit/@Model.ImageID" class="form-group">
        <button type="submit" class="btn btn-primary">Edit Image</button>
    </form>
    <div>
        @Html.ActionLink("Back to Dashboard", "Index")
    </div>
</div>

NBRHC/Views/Gallery/Edit.cshtml
@model NBRHC.Models.Gallery

@{
    ViewBag.Title = "Edit Image";
}

<div class="container">
    <h1>Edit Image</h1>
    @*Begin our form*@
    @using (Html.BeginForm("Edit", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ImageID)
    <div class="form-group">
        <hr />
        @*Image name*@
        <h2>@Model.ImageAlt</h2>
        <h4>@Model.ImageName</h4>
        <img src="~/images/gallery/@Model.ImageName.@Model.ImageType" class="imagePreview"/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Choose a file:</label>
            <input type="file" name="galleryimg" id="galleryimg" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageAlt, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.ImageAlt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImageAlt, "", new { @class = "text-danger" })
        </div>
        @*Submit button*@
        <button type="submit" class="btn btn-primary">Edit</button>
    </div>
    }
    <div>
        @Html.ActionLink("Back to Dashboard", "Index")
    </div>
</div>

NBRHC/Views/Gallery/List.cshtml
@model IEnumerable<NBRHC.Models.Gallery>

@{
    ViewData["Title"] = "Gallery Dashboard";
}
<head>

</head>
@if ((int)ViewData["UserState"] == 2)
{
    if (TempData["AddSuccess"] != null)
    {
        <div class="alert alert-success text-center" role="alert">
            <strong>Image successfully added</strong>
        </div>
    }
    else if (TempData["AddFail"] != null)
    {
        <div class="alert alert-danger text-center" role="alert">
            <strong>Failed to add image</strong>
            <div>File type must be: jpeg, jpg, png or gif</div>
        </div>
    }
    else if (TempData["EditSuccess"] != null)
    {
        <div class="alert alert-success text-center" role="alert">
            <strong>Image succeessfully edited</strong>
        </div>
    }
    else if (TempData["EditFail"] != null)
    {
        <div class="alert alert-danger text-center" role="alert">
            <strong>Failed to edit image</strong>
            <div>File type must be: jpeg, jpg, png or gif</div>
        </div>
    }
    else if (TempData["DeleteSuccess"] != null)
    {
        <div class="alert alert-success text-center" role="alert">
            <strong>Image succeessfully deleted</strong>
        </div>
    }
}
<div class="container">
    <h1>Gallery Dashboard</h1>
    <hr />
    @*If the user is not an admin they have to be an admin*@
    @if ((int)ViewData["UserState"] == 1)
    {
        <!-- Users that do not have an admin account must create an admin account in order to see Edit/Details/Delete -->
        <form method="get" action="/Admin/Create">
            <button type="submit" class="btn btn-primary">Create an Admin</button>
        </form>
    }
    @*If the user is not an admin they are not allowed to add to the gallery but they can see it*@
    else if ((int)ViewData["UserState"] == 0)
    {
        <div class="slideshow-container">
            @foreach (var item in Model)
            {
                <div class="mySlides fade">
                    <img src="~/images/gallery/@Html.DisplayFor(modelItem=> item.ImageName).@Html.DisplayFor(modelItem=> item.ImageType)" class="galleryImages" alt="@Html.DisplayFor(modelItem=>item.ImageAlt)" />
                </div>
            }
        </div>
    }
    @*If they are an admin they get full control over the application*@
    else if ((int)ViewData["UserState"] == 2)
    {
        //Add Button
        <form method="get" action="/Gallery/New">
            <button type="submit" class="btn btn-primary">Add Image</button>
        </form>
        <br />
        <br />
        //Gallery
        <div class="slideshow-container">
            @foreach (var item in Model)
            {
                <div class="mySlides fade">
                    <img src="~/images/gallery/@Html.DisplayFor(modelItem=> item.ImageName).@Html.DisplayFor(modelItem=> item.ImageType)" class="galleryImages" alt="@Html.DisplayFor(modelItem=>item.ImageAlt)" />
                </div>
            }
        </div>
        //Pagination
        <div id="paginationSummary">
            @ViewData["PaginationSummary"]
        </div>
        <div>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">@Html.ActionLink("Prev", "List", "Gallery", new { pagenum = ((int)ViewData["pagenum"] - 1) })</li>
                    <li class="page-item">@Html.ActionLink("Next", "List", "Gallery", new { pagenum = ((int)ViewData["pagenum"] + 1) })</li>
                </ul>
            </nav>
        </div>
        //Control
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        Alt
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ImageName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ImageAlt)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ImageID })
                            @Html.Raw(" | ")
                            @Html.ActionLink("Details", "Details", new { id = item.ImageID })
                            @Html.Raw(" | ")
                            @Html.ActionLink("Delete", "Delete", new { id = item.ImageID }, new { onclick = "return confirm('Are you sure you wish to delete this image?');" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

NBRHC/Views/Gallery/New.cshtml
@model NBRHC.Models.Gallery

@{
    ViewBag.Title = "Add Image";
}

@Html.ValidationSummary()


<div class="container">
    <h1>Upload Image</h1>

    @*Begin Form*@
    @using (Html.BeginForm("New", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label>Choose an image:</label>
                <input type="file" name="galleryimg" id="galleryimg" />
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ImageAlt, htmlAttributes: new { @class = "" })
                @Html.EditorFor(model => model.ImageAlt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageAlt, "", new { @class = "text-danger" })
            </div>
            @*Submit Button*@
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    }

    <div>
        @Html.ActionLink("Back to Dashboard", "Index")
    </div>
</div>