NBRHC/Models/Donation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NBRHC.Models
{
    public class Donation
    {
        [Key]
        public int DonationId { get; set; }

        //Each donation has an amount
        [Required, Display(Name = "Amount")]
        public double Amount { get; set; }

        
        //Each donation has a date
        [Required, StringLength(255), Display(Name = "Date")]
        public string Date { get; set; }
 
        [ForeignKey("DonationGoalId")]
        public int DonationGoalID { get; set; }

        public virtual DonationGoal DonationGoal { get; set; }

        //Each donation was made by a donor
        [ForeignKey("DonorId")]
        public int DonorId { get; set; }
        
        public virtual Donor Donor { get; set; }
    }
}

NBRHC/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using System.Web;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using NBRHC.Models;
using NBRHC.Models.ViewModels;
using NBRHC.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

namespace NBRHC.Controllers.Donations
{
    public class DonationController : Controller
    {
        //Database context
        private readonly NBRHCCMSContext db;

        //Dependencies to be able to get the current user
        //I used the code from Christine's example to be able to build the login functionality...
        private readonly UserManager<ApplicationUser> userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await userManager.GetUserAsync(HttpContext.User);


        public DonationController(NBRHCCMSContext context, UserManager<ApplicationUser> usermgr)
        {
            db = context;
            userManager = usermgr;
        }

        public async Task<IActionResult> Index()
        {
            return View(await db.Donations.ToListAsync());
        }

        public int GetUserState(ApplicationUser user)
        {
            //0: No user
            //1: User logged in
            //2: User logged in and is an admin

            if (user == null)
            {
                return 0;
            }
            else if(user.AdminID == null)
            {
                return 1;
            } else
            {
                var useradminid = user.AdminID;
                return 2;
            }
        }

        public async Task<ActionResult> Show(int id)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);
            Debug.WriteLine("donation id: " + id);

            if (userstate == 0)
            {
                ViewData["UserState"] = "Guest";
            }
            if (userstate == 1)
            {
                ViewData["UserState"] = "User";
            }
            if (userstate == 2)
            {
                ViewData["UserState"] = "Admin";
            }

            var donation =
               db.Donations
               .Include(d => d.Donor)
               .Include(d => d.DonationGoal)
               .Where(d => d.DonationId == id)
               .FirstOrDefault();
            
            return View(donation);
        }

        public async Task<ActionResult> New()
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);

            if (userstate == 0)
            {
                return RedirectToAction("List");
            }
            else
            {
                //Ideally only an admin can add a new  user but to make it easier to add
                //stuff for testing purposes, I'm making it so a user can add a donation.
                DonationAdd donationaddview = new DonationAdd();
                donationaddview.donors = db.Donors.ToList();
                donationaddview.donationgoals = db.DonationGoals.ToList();
                return View(donationaddview);
            }
        }
        
        [HttpPost]
        //This actually does the New action.
        //We use HttpPost to specify the that the form is using post.
        //MAKE SURE the parameters match the name of the html name attributes.
        public async Task<ActionResult> Create(int formamt, int donorid, int donationgoalid)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);
            Debug.WriteLine("Form amt: " + formamt);
            Debug.WriteLine("Donor id: " + donorid);
            Debug.WriteLine(DateTime.Today.ToString("yyyy-MM-dd"));

            if (userstate == 0)
            {
                return RedirectToAction("List");
            }
            else
            {
                //QUERY
                //second thing, build a query that inserts a new donation into the donations table
                var query = "INSERT INTO donations (Amount, Date, DonationGoalId, DonorId)";
                query += "VALUES (@amt, @dat, @dgid, @did)";
                SqlParameter[] sqlparams = new SqlParameter[4];
                sqlparams[0] = new SqlParameter("@amt", formamt);
                sqlparams[1] = new SqlParameter("@dat", DateTime.Today.ToString("yyyy-MM-dd"));
                sqlparams[2] = new SqlParameter("@dgid", donationgoalid);
                sqlparams[3] = new SqlParameter("@did", donorid);

                //ALGORITHM
                //third thing, run the query into the database
                db.Database.ExecuteSqlCommand(query, sqlparams);
                return RedirectToAction("List");
            }
        }

        public async Task<ActionResult> List(int pagenum)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);

            if (userstate == 0)
            {
                ViewData["UserState"] = "Guest";
            }
            if (userstate == 1)
            {
                ViewData["UserState"] = "User";
            }
            if (userstate == 2)
            {
                ViewData["UserState"] = "Admin";
            }

            /**********************PAGINATION****************************/

            var donations = await db.Donations.Include(d => d.DonationGoal).ToListAsync();
            //var _donors = await _context.Donations.Include(d => d.Donor).ToListAsync();
            //2 Get the size of the query of all records.
            int donationcount = donations.Count();
            //add a perpage, sets the number of donations per page.
            int perpage = 5;
            //Dividing total number of donations with perpage, and using Math.ceiling
            //to determine the total number of pages.
            int maxpage = (int)Math.Ceiling((decimal)donationcount / perpage) - 1;
            //Making sure we don't go to a page that's out of bounds
            if (maxpage < 0)
                { maxpage = 0; }
            if (pagenum < 0)
                { pagenum = 0; }
            if (pagenum > maxpage)
                { pagenum = maxpage; }
            //Skip the first X pages where X is number of pages timesnumber of items per page.
            int start = perpage * pagenum;
            //Sending information to the view
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            //Sending information to the view if the view is not on the first page of results.
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pagenum + 1).ToString() + " of " + (maxpage + 1).ToString();
            }
            //Like an SQL query we list the donations that we need on each page
            //.skip: Offset query by this many records
            //.take: Take only this many records.
            donations = await db.Donations.Include(d => d.Donor).Skip(start).Take(perpage).ToListAsync();
            return View(donations);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            //Ideally only an admin can delete donations but I'm making it
            //so users can too because it's convenient for testing...
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);

            if (userstate == 0)
            {
                return RedirectToAction("List");
            } else if (userstate == 1)
            {
                string query = "DELETE FROM donations WHERE DonationID = @id";
                SqlParameter param = new SqlParameter("@id", id);
                db.Database.ExecuteSqlCommand(query, param);
                return RedirectToAction("List");
            } else
            {
                string query = "DELETE FROM donations WHERE DonationID = @id";
                SqlParameter param = new SqlParameter("@id", id);
                db.Database.ExecuteSqlCommand(query, param);
                return RedirectToAction("List");
            }

            

        }

        /*The method that shows the edit page*/
        
        public async Task<ActionResult> Edit(int id)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);

            if (userstate == 0)
            {
                return RedirectToAction("List");
            }
            else
            {
                DonationEdit donationedit = new DonationEdit();
                donationedit.DonationGoals = db.DonationGoals.ToList();
                donationedit.Donors = db.Donors.ToList();

                donationedit.Donation = db.Donations
                    .Where(d => d.DonationId == id)
                    .FirstOrDefault();

                return View(donationedit);
            }
        }

        /*This does the edit operation*/
        [HttpPost]
        public async Task <ActionResult> Edit(int id, int amount, string date, int donationgoalid, int donorid)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserState(user);

            Debug.WriteLine("User state: " + userstate);

NBRHC/Views/Donation/Edit.cshtml
@model NBRHC.Models.ViewModels.DonationEdit


<h2>Edit</h2>
@{
    ViewData["Title"] = "Edit";
}
<head>
    <link href="donationstyle.css" rel="stylesheet" type="text/css">
</head>

<div class="crud-nav">
    <div>
        @Html.ActionLink("BACK TO LIST", "list", "donation")
    </div>
    <div>
        @Html.ActionLink("BACK TO SHOW", "show", "donation")
    </div>
</div>

<form method="post" action="/Donation/Edit/@Model.Donation.DonationId">
    <label for="amount">Amount:</label>
    <input type="text" name="amount" value="@Model.Donation.Amount" />
    <label for="date">Date:</label>
    <input type="text" name="date" value="@Model.Donation.Date" />
    <div>
        <label>Donation Goal:</label>
        <!--Christine bitbucket code-->
        <select name="donationgoalid">
            @{
                string attr = "";
            }
            @foreach (var donationgoal in Model.DonationGoals)
            {
                attr = "false";
                if (donationgoal.DonationGoalId == Model.Donation.DonationGoalID) { attr = "true"; }
                <option value="@(donationgoal.DonationGoalId)" selected="@(attr)">goal of @(donationgoal.Goal) from @(donationgoal.StartDate) until @(donationgoal.EndDate)</option>

            }
        </select>
    </div>
    <!--Add the donor and a submit button-->
    <div>
        <label>Donor:</label>

        <select name="donorid">
            @foreach (var donor in Model.Donors)
            {
                <option value="@(donor.DonorId)">@(donor.firstName) @(donor.lastName)</option>
            }
        </select>
    </div>
    <input type="submit" name="formsubmit" value="OK">
</form>

NBRHC/Views/Donation/List.cshtml
@model IEnumerable<NBRHC.Models.Donation>

@{
    ViewData["Title"] = "Donations";
}



<div class="crud-nav">
    <div style="font-size:20pt;">
        <div id="debug">
            <!--ViewData["UserState"]-->
        </div>
        <!--Just using a switch statement like in the example because it's
            convenient, I could also do if/else statements like I usually do...-->
        @{
            

            switch (ViewData["UserState"])
            {
                case "Guest": @Html.ActionLink("SIGN UP!", "List", "Donation"); break;
                case "User": @Html.ActionLink("ADD NEW", "New", "Donation"); break;
                case "Admin": @Html.ActionLink("ADD NEW", "New", "Donation"); break;
            }
        }

    </div>

    <div style="font-size:20pt;">
        @Html.ActionLink("TO DONORS", "list", "donor")
    </div>

    <div style="font-size:20pt;">
        @Html.ActionLink("TO DONATION GOALS", "list", "donationgoal")
    </div>
</div>

<div id="donations">
    <div id="pagination-top">
        @ViewData["PaginationSummary"]
        @Html.ActionLink("<- Prev", "List", "Donation",
        new { pagenum = ((int)ViewData["pagenum"]-1)})

        @Html.ActionLink("Next ->", "List", "Donation",
        new { pagenum = ((int)ViewData["pagenum"] + 1) })
    </div>
    @foreach (var donation in @Model)
    {
        <div class="donation" style="background-color:lightgrey;">
            <h4>
                $@donation.Amount
                <span class="donation__donor">from @donation.Donor.firstName @donation.Donor.lastName</span>
                <span class="donation__date">on @donation.Date</span>

            </h4>
            <p>
                Towards the goal for $@donation.DonationGoal.Goal
                from @donation.DonationGoal.StartDate until @donation.DonationGoal.EndDate
            </p>
            @Html.ActionLink("View Donation", "Show", "Donation", new { id = donation.DonationId })
        </div>
    }
    <div id="pagination-bottom">
        @ViewData["PaginationSummary"]

        @Html.ActionLink("<- Prev", "List", "Blog",
        new { pagenum = ((int)ViewData["pagenum"]-1)})

        @Html.ActionLink("Next ->", "List", "Blog",
        new { pagenum = ((int)ViewData["pagenum"] + 1) })
    </div>
</div>

NBRHC/Views/Donation/New.cshtml
@model NBRHC.Models.ViewModels.DonationAdd

@{
    ViewData["Title"] = "New Donation";
}

<head>
    <link href="donationstyle.css" rel="stylesheet" type="text/css">
</head>
<div class="crud-nav">
    <div style="font-size:24pt;">
        @Html.ActionLink("BACK TO LIST", "list", "donation")
    </div>
</div>
<form method="post" action="/Donation/Create">
    <h1 class="new-donation">New Donation</h1>
    <!--Fields for donation form:
        Amount
        Donor ddl (Needs view model)-->
    <div>
        <label for="form-amt">Amount:</label>
        <input type="text" name="formamt">
    </div>
    <div>
        <label>Donor:</label>
        <select name="donorid">
            @foreach (var donor in @Model.donors)
            {
                <option value="@(donor.DonorId)">@(donor.firstName) @(donor.lastName)</option>
            }
        </select>
    </div>
    <div>
        <label>Donation goal:</label>
        <select name="donationgoalid">
            @foreach(var donationgoal in Model.donationgoals)
            {
                <option value="@(donationgoal.DonationGoalId)">@(donationgoal.StartDate) @(donationgoal.EndDate)</option>
            }
        </select>
    </div>
    <div>
        <input type="submit" value="OK">
    </div>
</form>

NBRHC/Views/Donation/Refund.cshtml
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NBRHC.Views.Donations
{
    public class Refund
    {
    }
}

NBRHC/Views/Donation/Show.cshtml
@model NBRHC.Models.Donation

<head>
    <link href="donationstyle.css" rel="stylesheet" type="text/css">
</head>

<div id="debug">
    @ViewData["UserState"]
</div>

<div class="crud-nav">
    <!--Put navigation action links here-->
    @Html.ActionLink("BACK TO LIST", "list", "donation")
</div>


<h1>Show Donation</h1>

<p><span style="font-weight:bold;">Date:</span> @Model.Date</p>
<p><span style="font-weight:bold;">Amount:</span> $@Model.Amount</p>
<p>
    <span style="font-weight:bold;">Donation goal:</span>
    $@Model.DonationGoal.Goal from @Model.DonationGoal.StartDate until @Model.DonationGoal.EndDate
</p>
<p><span style="font-weight:bold;">Donor name:</span> @Model.Donor.firstName @Model.Donor.lastName</p>

<div>
@{
    switch (ViewData["UserState"])
    {
        case "Guest": break;
        case "User": @Html.ActionLink("EDIT", "Edit", "Donation", new { id = Model.DonationId });
            @Html.ActionLink("DELETE", "Delete", "Donation", new { id = Model.DonationId });
            break;
        case "Admin": @Html.ActionLink("EDIT", "Edit", "Donation", new { id = Model.DonationId });
            @Html.ActionLink("DELETE", "Delete", "Donation", new { id = Model.DonationId });
            break;
    }
}
</div>