NBRHC/Models/Testimonial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace NBRHC.Models
{
    public class Testimonial
    {
        [Key]
        public int TestimonialID { get; set; }

        [Required, StringLength(255), Display(Name = "Name")]
        public string TestimonialName { get; set; }

        [Required, StringLength(255), Display(Name = "Email")]
        public string TestimonialEmail { get; set; }

        [DataType(DataType.Date), Display(Name = "Date")]
        public DateTime TestimonialDate { get; set; }

        [Required, StringLength(255), Display(Name = "Title")]
        public string TestimonialTitle { get; set; }

        [Required, StringLength(255), Display(Name = "Statement")]
        public string TestimonialStatement { get; set; }

        [Required, Display(Name = "Approve")]
        public bool TestimonialApprove { get; set; }

        [Required, Display(Name = "Publish")]
        public bool TestimonialPublish { get; set; }

        [Range(typeof(bool), "true", "true", ErrorMessage = "Must be checked"), Display(Name = "I agree to have this published")]
        public bool TestimonialPublishAgreement { get; set; }

        //Referenced Christines MVC example
        //Picture
        //1 => Picture exists (in imgs/makeupproducts/{id}.ImgType)
        //0 => Picture doesn't exist
        public int HasPic { get; set; }

        //Accepted image formats (jpg/jpeg/png/gif)
        public string ImgFilename { get; set; }

    }
}

NBRHC/Controllers/TestimonialController.cs
//Referenced Christine's code
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using NBRHC.Models;
using NBRHC.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
namespace NBRHC.Controllers
{
    public class TestimonialController : Controller
    {
        private readonly NBRHCCMSContext db;
        private readonly IHostingEnvironment _env;
        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public TestimonialController(NBRHCCMSContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _env = env;
            _userManager = usermanager;
        }

        public int GetUserDetails(ApplicationUser user)
        {
            //UserState
            //Referenced Christines code
            //0 => Public user 
            //1 => User but has no admin account 
            //2 => User has admin account 
            if (user == null) return 0;
            if (user.AdminID == null) return 1; //User has no admin account 
            else if (user.AdminID != null) return 2; //user has admin account
            else return -1; //something went wrong
        }

        public Testimonial CheckImage(Testimonial testimonial, IFormFile testimonialImg)
        {
            //Referenced Christines code
            if (testimonialImg?.Length > 0)
            {
                //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                var validTypes = new[] { "jpeg", "jpg", "png", "gif" };
                var extension = Path.GetExtension(testimonialImg.FileName).Substring(1);
                var webRoot = _env.WebRootPath;
                if (validTypes.Contains(extension))
                {
                    string path = Path.Combine(webRoot, "images/testimonials");

                    if (testimonial.ImgFilename != null)
                    {
                        path = Path.Combine(path, testimonial.ImgFilename);
                        //Deletes previous image 
                        //Referenced https://stackoverflow.com/questions/37204268/how-to-delete-the-uploaded-files-in-the-app-data-uploads-folder-asp-net-mvc
                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);
                        }
                    }
                    //generic .img extension, web translates easily.
                    //Referenced: https://stackoverflow.com/questions/12457084/saving-uploaded-file-with-unique-name-in-folder
                    string filename = System.DateTime.Now.ToString("ddMMyyhhmmss") + "." + extension;

                    //get a direct file path to imgs/testimonials/
                    path = Path.Combine(webRoot, "images/testimonials");
                    path = Path.Combine(path, filename);

                    //save the file
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        testimonialImg.CopyTo(stream);
                    }

                    //let the model know that there is a picture with an extension
                    testimonial.HasPic = 1;
                    testimonial.ImgFilename = filename;
                }
            }
            return testimonial;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //Testimonial/Details/
        public async Task<ActionResult> Details(int? id)
        {
            //bad request or page with that id doesn't exist 
            if (id == null || db.Testimonials.Find(id) == null)
            {
                return NotFound();
            }

            Testimonial testimonial = db.Testimonials.Find(id);
            var user = await GetCurrentUserAsync();
            var userstate = GetUserDetails(user);
            ViewData["UserState"] = userstate;

            //if user has a user account 
            if (userstate > 0)
            {
                return View(testimonial);
            }
            else
            {
                //Public website visitors cannot access pages that aren't published 
                if (testimonial.TestimonialPublish == true) return View(testimonial);
                else return Forbid();
            }
        }

        public async Task<ActionResult> List(int pageNum)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserDetails(user);

            //information about the type of user 
            ViewData["UserState"] = userstate;

            List<Testimonial> testimonials;
            int perpage;

            if (userstate > 0)
            {
                //if there is a user 
                //users and admin users can see list of testimonials 
                testimonials = await db.Testimonials.ToListAsync();
                perpage = 15;
            }
            else
            {
                //Public website visitors can only view published pages 
                testimonials = await db.Testimonials.Where(t => t.TestimonialPublish.Equals(true)).ToListAsync();
                perpage = 3;
            }

            /*Pagination - Referenced Christines code */
            int pageCount = testimonials.Count();
            int maxpage = (int)Math.Ceiling((decimal)pageCount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pageNum < 0) pageNum = 0;
            if (pageNum > maxpage) pageNum = maxpage;
            int start = perpage * pageNum;
            ViewData["pagenum"] = (int)pageNum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] =
                    (pageNum + 1).ToString() + " of " +
                    (maxpage + 1).ToString();
            }

            return View(testimonials.Skip(start).Take(perpage).ToList());
        }

        // GET: Testimonial/New
        public async Task<ActionResult> New()
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserDetails(user);
            ViewData["UserState"] = userstate;

            //Users and admin users cannot create testimonials
            if (userstate > 0)
            {
                return Forbid();
            }
            else
            {
            //Website visitors can write a testimonial
                return View();
            } 
        
        }

        // POST: Testimonial/New
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> New([Bind("TestimonialID, TestimonialName, TestimonialEmail, " +
            " TestimonialTitle, TestimonialStatement", "TestimonialPublishAgreement")] Testimonial testimonial, IFormFile testimonialImg)
        {
            var user = await GetCurrentUserAsync();
            var userstate = GetUserDetails(user);
      
            //if there is a user
            if (userstate > 0) return Forbid(); //Users and admin users cannot create testimonials
            else
            {
                //Website visitors can write a testimonial
                //By default testimonials do not have images
                testimonial.HasPic = 0;

                //Checks to see if public user uploaded a picture with their testimonial 
                testimonial = CheckImage(testimonial, testimonialImg);

                //Checks against validation attributes in model 
                if (ModelState.IsValid)
                {
                    //default values
                    testimonial.TestimonialDate = DateTime.Now;
                    testimonial.TestimonialApprove = false;
                    testimonial.TestimonialPublish = false;

                    db.Testimonials.Add(testimonial);
                    db.SaveChanges();
                    return RedirectToAction("List");
                }
                else
                {
                    return View();
                }
            }
        }

        public async Task<ActionResult> Edit(int? id)
        {
            //bad request or page with that id doesn't exist 
            if (id == null || db.Testimonials.Find(id) == null)
            {
                return NotFound();
            }
            else
            {
                Testimonial testimonial = db.Testimonials.Find(id);
                var user = await GetCurrentUserAsync();
                var userstate = GetUserDetails(user);

                //can't edit testimonial unless they have an admin account
                if (userstate < 2)
                {
                    return Forbid();
                }
                else
                {
                    return View(testimonial);
                }
            }
        }

        
        //POST: Testimonial/Edit 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("TestimonialID, TestimonialName, TestimonialDate, TestimonialEmail, TestimonialTitle, " +
            "TestimonialStatement, TestimonialApprove, TestimonialPublish, TestimonialPublishAgreement, HasPic, ImgFilename")] Testimonial testimonial, IFormFile testimonialImg)
        {
           //Checks user 

NBRHC/Views/Testimonial/Details.cshtml
@model NBRHC.Models.Testimonial

@{
    ViewBag.Title = "Details";
}

<div class="item flex-container">
    <div class="testimonial-img-container">
        @if (Model.HasPic == 1)
        {
            <img src="~/images/testimonials/@Model.ImgFilename" alt="@Model.TestimonialName" />

        }
    </div>
    <div class="testimonial-text">
        <!-- if user is an admin -->
        @if ((int)ViewData["userstate"] == 2)
        {
            <div>
                <span class="bold">Email:</span> @Model.TestimonialEmail
                <br />
                <span class="bold">Date Submitted: </span> @Model.TestimonialDate
            </div>
        }
        <h3>@Model.TestimonialTitle</h3>
        <div class="quote">"@Model.TestimonialStatement"</div>
        <div class="testimonial-author">- @Model.TestimonialName</div>

        <!-- if user is an admin, they can see the approve and publish status -->
        @if ((int)ViewData["userstate"] == 2)
        {
            <br />
            <div>
                <label for="testimonialApprove">Approve</label> 
                <span id="tesitmonialApprove">
                    @Html.DisplayFor(model => model.TestimonialApprove)
                </span>
                <br />
                <label for="testimonialPublish">Publish</label>
                <span id="testimonialPublish">
                    @Html.DisplayFor(model => model.TestimonialPublish)
                </span>
            </div>
        }
    </div>
</div>

<!--Referenced Christines code-->
<div>
    <!-- if user is an admin -->
    @if ((int)ViewData["userstate"] == 2)
    {
        @Html.ActionLink("Edit", "Edit/" + Model.TestimonialID, "Testimonial", null, new { @class = "btn btn-default" })
        @Html.Raw(" ");
        @Html.ActionLink("Delete", "Delete/" + Model.TestimonialID, "Testimonial", null, new { @class = "btn btn-default" })
    }
    <br />
    <br />
    @Html.ActionLink("Back To List", "Index", "Testimonial", null, new { @class = "btn btn-default" })
</div>

NBRHC/Views/Testimonial/Edit.cshtml
@model NBRHC.Models.Testimonial

@{
    ViewBag.Title = "Edit";
}

<form method="POST" action="/Testimonial/Edit" enctype="multipart/form-data" class="form-container">
    <h2>Edit @Model.TestimonialTitle</h2>
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!--Hidden fields-->
    @Html.HiddenFor(model => model.TestimonialID)
    @Html.HiddenFor(model => model.TestimonialDate)
    @Html.HiddenFor(model => model.TestimonialPublishAgreement)
    @Html.HiddenFor(model => model.HasPic)
    @Html.HiddenFor(model => model.ImgFilename)

    <div class="form-group-container">
        @Html.LabelFor(model => model.TestimonialName)
        <div>
            <!--Editor for generates input element based on datatype-->
            @Html.EditorFor(model => model.TestimonialName)
            @Html.ValidationMessageFor(model => model.TestimonialName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group-container">
        @Html.LabelFor(model => model.TestimonialEmail)
        <div>
            @Html.EditorFor(model => model.TestimonialEmail)
            @Html.ValidationMessageFor(model => model.TestimonialEmail, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group-container">
        @Html.LabelFor(model => model.TestimonialTitle)
        <div>
            @Html.EditorFor(model => model.TestimonialTitle)
            @Html.ValidationMessageFor(model => model.TestimonialTitle, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group-container">
        @Html.LabelFor(model => model.TestimonialStatement)
        <div>
            @Html.EditorFor(model => model.TestimonialStatement)
            @Html.ValidationMessageFor(model => model.TestimonialStatement, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group-container">
        @Html.LabelFor(model => model.TestimonialApprove)
        @Html.EditorFor(model => model.TestimonialApprove)
        <div>
            @Html.ValidationMessageFor(model => model.TestimonialApprove, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group-container">
        @Html.LabelFor(model => model.TestimonialPublish)
        @Html.EditorFor(model => model.TestimonialPublish)
        <div>
            @Html.ValidationMessageFor(model => model.TestimonialPublish, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group-container">
        <label for="testimonialImg">Picture</label>
        <!--If the testimonial has an image, displays the image-->

        @if (Model.HasPic == 1)
        {
        <div class="testimonial-img-container">
            <div class="img-container">
                <img src="~/images/testimonials/@(Model.ImgFilename)" alt="@Model.TestimonialName" />
            </div>
            <br />
        </div>
        }
        else
        {
            <span>None</span>
        }
        <br />
        <input type="file" name="testimonialImg" id="testimonialImg" />
        </div>
    <div class="form-group-container">
        <input type="submit" value="Save" class="btn btn-default" />
        @Html.ActionLink("Cancel", "Details/" + Model.TestimonialID, "Testimonial", null, new { @class = "btn btn-default" })
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index", "Testimonial", null, new { @class = "btn btn-default"})
    </div>
</form>

NBRHC/Views/Testimonial/List.cshtml
<!--Referenced Christines code-->
@model IEnumerable<NBRHC.Models.Testimonial>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_UnwrappedLayout.cshtml";
}

<div id="testimonial-banner" class="banner flex-container">
    <h2 class="banner-title wrapper">Patient Testimonials</h2>
</div>

<div id="testimonials">
    @if ((int)ViewData["userstate"] != 2)
    {
        <div class="button-container wrapper">
            @if ((int)ViewData["userstate"] == 1)
            {
                <!-- Users that do not have an admin account must create an admin account in order to see Edit/Details/Delete -->
                @Html.ActionLink("Create an Admin", "Create", "Admin")
            }
            else if ((int)ViewData["userstate"] == 0)
            {
                <!-- Website visitors can write a testimonial-->
                @Html.ActionLink("Write a Testimonial", "New", "Testimonial", null, new { @id="write-testimonial-btn", @class = "button" })
            }
        </div>
    }

        <div id="testimonial-list" class="flex-container wrapper">
            <div class="pagination">
                <!--Referenced Christines code, pagination-->
                <!--Pagination only shows if theres more than one page-->
                @if ((string)ViewData["PaginationSummary"] != "")
                {
                    @ViewData["PaginationSummary"]
                    @Html.Raw(" ");
                    @Html.ActionLink("Prev", "List", "Testimonial", new { pagenum = ((int)ViewData["pagenum"] - 1) })
                    @Html.Raw(" ");
                    @Html.ActionLink("Next", "List", "Testimonial", new { pagenum = ((int)ViewData["pagenum"] + 1) })
                }
            </div>

            <!--If viewer is user or admin user, they can see the list of all testimonials
             If viewer is an admin, they can select the edit, details, and delete options
            If view is a public website visitor, they can only see list of published testimonials-->

            <!--View for public website visitor-->
            @if ((int)ViewData["userstate"] == 0)
            {
                @foreach (var testimonial in Model)
                {
                    <div class="item flex-container">
                        <div class="testimonial-img-container">
                            @if (testimonial.HasPic == 1)
                            {
                                <img src="~/images/testimonials/@testimonial.ImgFilename" alt="@testimonial.TestimonialName" />

                            }
                        </div>
                        <div class="testimonial-text">
                            <h3 class="quote">"@testimonial.TestimonialTitle"</h3>
                            <div class="testimonial-author">- @testimonial.TestimonialName</div>
                            <div class="button-container">
                                @Html.ActionLink("Read More", "Details", new { id = testimonial.TestimonialID }, new { @class = "read-more" })
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <!--View for users and admin users (They can see published testimonials, approved testimonials, 
                    and testimonials under review-->

                <!--Published Testimonials table-->
                <h3>Published Testimonials</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.TestimonialTitle)</th>
                            <th>@Html.DisplayNameFor(model => model.TestimonialStatement)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var testimonial in Model)
                        {
                            if (testimonial.TestimonialPublish)
                            {
                                <tr>
                                    <td>@testimonial.TestimonialTitle</td>
                                    <td>@testimonial.TestimonialStatement</td>
                                    <!--If viewer is an admin user they can see the options edit, details, and delete-->
                                    <td>
                                        @if ((int)ViewData["userstate"] == 2)
                                        {
                                            @Html.ActionLink("Edit", "Edit", new { id = testimonial.TestimonialID })
                                            @Html.Raw(" | ")
                                            @Html.ActionLink("Details", "Details", new { id = testimonial.TestimonialID })
                                            @Html.Raw(" | ")
                                            @Html.ActionLink("Delete", "Delete", new { id = testimonial.TestimonialID })
                                        }
                                        else
                                        {
                                            @Html.ActionLink("Details", "Details", new { id = testimonial.TestimonialID })
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table> <!--End of Published Testimonials table-->

                <!--Approved Testimonials table-->
                <h3 class="title">Approved Testimonials</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.TestimonialTitle)</th>
                            <th>@Html.DisplayNameFor(model => model.TestimonialStatement)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var testimonial in Model)
                        {
                            if (testimonial.TestimonialApprove && !testimonial.TestimonialPublish)
                            {
                                <tr>
                                    <td>@testimonial.TestimonialTitle</td>
                                    <td>@testimonial.TestimonialStatement</td>
                                    <!--If viewer is an admin user they can see the options edit, details, and delete-->
                                    <td>
                                        @if ((int)ViewData["userstate"] == 2)
                                        {
                                            @Html.ActionLink("Edit", "Edit", new { id = testimonial.TestimonialID })
                                            @Html.Raw(" | ")
                                            @Html.ActionLink("Details", "Details", new { id = testimonial.TestimonialID })
                                            @Html.Raw(" | ")
                                            @Html.ActionLink("Delete", "Delete", new { id = testimonial.TestimonialID })
                                        }
                                        else
                                        {
                                            @Html.ActionLink("Details", "Details", new { id = testimonial.TestimonialID })
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table> <!--End of Approved Testimonials table-->

                <!--Testimonials to be Reviewed table-->
                <h3 class="title">Testimonials to be Reviewed</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.TestimonialTitle)</th>
                            <th>@Html.DisplayNameFor(model => model.TestimonialStatement)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var testimonial in Model)
                        {
                            if (!testimonial.TestimonialApprove && !testimonial.TestimonialPublish)
                            {
                                <tr>
                                    <td>@testimonial.TestimonialTitle</td>
                                    <td>@testimonial.TestimonialStatement</td>
                                    <!--If viewer is an admin user they can see the options edit, details, and delete-->
                                    <td>
                                        @if ((int)ViewData["userstate"] == 2)
                                        {
                                            @Html.ActionLink("Edit", "Edit", new { id = testimonial.TestimonialID })
                                            @Html.Raw(" | ")
                                            @Html.ActionLink("Details", "Details", new { id = testimonial.TestimonialID })
                                            @Html.Raw(" | ")
                                            @Html.ActionLink("Delete", "Delete", new { id = testimonial.TestimonialID })
                                        }
                                        else
                                        {
                                            @Html.ActionLink("Details", "Details", new { id = testimonial.TestimonialID })
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table> <!--End of Testimonials to be Reviewed table-->
            }
        </div> <!--End of testimonial list-->
</div>

NBRHC/Views/Testimonial/New.cshtml
@model NBRHC.Models.Testimonial

@{
    ViewBag.Title = "New";
}

<form method="POST" action="/Testimonial/New" enctype="multipart/form-data" class="form-container">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <h2>Write a Testimonial</h2>
    <div>
        <div class="form-group-container">
            @Html.LabelFor(model => model.TestimonialName)
            <div>
                @Html.EditorFor(model => model.TestimonialName)
                @Html.ValidationMessageFor(model => model.TestimonialName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group-container">
            @Html.LabelFor(model => model.TestimonialEmail)
            <div>
                @Html.EditorFor(model => model.TestimonialEmail)
                @Html.ValidationMessageFor(model => model.TestimonialEmail, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group-container">
            @Html.LabelFor(model => model.TestimonialTitle)
            <div>
                @Html.EditorFor(model => model.TestimonialTitle)
                @Html.ValidationMessageFor(model => model.TestimonialTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group-container">
            @Html.LabelFor(model => model.TestimonialStatement)
            <div>
                @Html.EditorFor(model => model.TestimonialStatement)
                @Html.ValidationMessageFor(model => model.TestimonialStatement, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group-container">
            <label for="testimonialImg">Picture</label>
            <input type="file" name="testimonialImg" id="testimonialImg" />
        </div>
        <br />
        <div class="form-group-container">
            @Html.LabelFor(model => model.TestimonialPublishAgreement)
            <div>
                @Html.EditorFor(model => model.TestimonialPublishAgreement)
                @Html.ValidationMessageFor(model => model.TestimonialPublishAgreement, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group-container">
            <input type="submit" value="Submit" class="btn btn-default" />
            @Html.ActionLink("Cancel", "Index", "Testimonial", null, new { @class = "btn btn-default" })
        </div>
    </div>
</form>